<?php

namespace BlogJF\BlogBundle\Repository;

/**
 * billetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilletRepository extends \Doctrine\ORM\EntityRepository
{
    public function ListePublishedByDateDESC()
    {
        $qb = $this
            ->createQueryBuilder('b')
            ->where('b.published = :published')
            ->setParameter('published', True)
            ->addOrderBy('b.date', 'DESC')
        ;
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function ListeByDateDESC()
    {
        $qb = $this
            ->createQueryBuilder('b')
            ->addOrderBy('b.date', 'DESC')
        ;
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
