<?php

namespace BlogJF\BlogBundle\Repository;

/**
 * commentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    function getCommentaireById($billetId)
    {
        $qb = $this
            ->createQueryBuilder('c')
            ->where('c.billet = :billet_id')
            ->addorderBy('c.parentId, c.id')
            ->setParameter('billet_id', $billetId)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}

/*SELECT id, billet_id, date, auteur, commentaire, parent_id FROM commentaire
UNION
(SELECT C.id, C.billet_id, C.date, C.auteur, C.commentaire, C.parent_id
   FROM commentaire AS C
   WHERE C.billet_id = 7
   INNER JOIN commentaire ON commentaire.id = C.parent_id)*/