login:
    path: /login
    defaults:
        { _controller: BlogJFBlogBundle:Security:login }

logout:
    path: /logout

blog_jf_blog:
    resource: "@BlogJFBlogBundle/Resources/config/routing.yml"
    prefix:   /
